Edit page
MaxPoon/TPCC-YEC-Soccer-Team-Mini-Program pull request #5
Opened 2019-01-26 06:53 UTC by MAXI0008

2019-01-26 14:00 UTC, MAXI0008 commented
Edit training information page


<img width="376" alt="screenshot 2019-01-26 at 9 58 05 pm" src="https://user-images.githubusercontent.com/30583988/51788153-b91d1980-21b5-11e9-8c87-ffa76c6cce2e.png">

2019-01-26 14:16 UTC, MaxPoon requested changes

2019-01-26 14:16 UTC, MaxPoon commented on client/pages/editntc/editntc.wxml
> +      </view>
Can you make it an date picker, and set it to next Sunday 2pm by default? Eventually we need to send the data to backend. Having a date picker makes it easier to standardize the format of data sent to the backend.

2019-01-26 14:16 UTC, MaxPoon commented on client/pages/editntc/editntc.js
> +    console.log('the form of editing notice was submitted：', e.detail.value)
I guess this is for testing purpose. It's not a great idea to expose your log messages in production code.

2019-01-26 14:16 UTC, MaxPoon commented on client/pages/editntc/editntc.json
> +    "navigationBarTitleText": "TPCC YEC Soccer Team",
Do we really need this line as it's the same as the setting in `app.json`?

2019-01-26 14:16 UTC, MaxPoon commented on client/pages/editntc/editntc.wxss
> +
Remove the extra lines.

2019-01-26 14:21 UTC, MAXI0008 commented on client/pages/editntc/editntc.wxss
> +
No problem.

2019-01-26 14:22 UTC, ERICCYS commented on client/pages/editntc/editntc.json
> +    "navigationBarTitleText": "TPCC YEC Soccer Team",
This one is just to display a differnt style of top bar, if we remove these lines, the display will look like this. Do we prefer this display with these lines removed?
<img width="376" alt="screenshot 2019-01-26 at 10 20 59 pm" src="https://user-images.githubusercontent.com/30583988/51788419-d4d5ef00-21b8-11e9-8ec4-777254905e3b.png">

2019-01-26 14:23 UTC, ERICCYS commented on client/pages/editntc/editntc.js
> +    console.log('the form of editing notice was submitted：', e.detail.value)
Sure

2019-01-26 15:51 UTC, ERICCYS commented on client/pages/editntc/editntc.wxml
> +      </view>
I have chosen a date picker from the WeChat official doc, and the page now looks like this when choosing the date time

<img width="376" alt="screenshot 2019-01-26 at 11 46 41 pm" src="https://user-images.githubusercontent.com/30583988/51789562-cdb4de00-21c4-11e9-803b-0dd1ba9fbcd7.png">

Now the data formate shall be standardized, and there are many formats available.

One problem is that I put a Sunday there since I found that there should be some text or view there so that user can click on and choose the time. Considering most of our training happens on Sunday. I choose Sunday.

<img width="376" alt="screenshot 2019-01-26 at 11 50 35 pm" src="https://user-images.githubusercontent.com/30583988/51789599-32703880-21c5-11e9-96f7-d115f1a3eab8.png">

2019-01-28 15:05 UTC, MaxPoon approved these changes

2019-01-28 15:05 UTC, merged